(define (problem prob-snack) 
    (:domain child-snack) 
    (:objects 
    kitchen table1 table2 table3  -  place
    child1 child2 child3 child4 child5 child6  -  child
    tray1 tray2  -  tray
)
    (:init 
    (at tray1 kitchen)
    (at tray2 kitchen)
    (allergic_gluten child1)
    (allergic_gluten child5)
    (not_allergic_gluten child2)
    (not_allergic_gluten child3)
    (not_allergic_gluten child4)
    (not_allergic_gluten child6)
    (waiting child1 table2)
    (waiting child2 table1)
    (waiting child3 table3)
    (waiting child4 table2)
    (waiting child5 table1)
    (waiting child6 table1)
    ;;(= (notexist ) 8)
    (= (Nsandwich-ontray tray1) 0)
    (= (Nsandwich-ontray tray2) 0)
    (= (Nsandwich-at_kitchen_sandwich_no_gluten_sandwich ) 0)
    (= (Nbread-portion-at_kitchen_bread_no_gluten_bread ) 2)
    (= (Ncontent-portion-at_kitchen_content_no_gluten_content ) 2)
    (= (Nbread-portion-at_kitchen_bread ) 4)
    (= (Ncontent-portion-at_kitchen_content ) 4)
    (= (Nsandwich-at_kitchen_sandwich ) 0)
    (= (Nsandwich-ontray_no_gluten_sandwich tray1) 0)
    (= (Nsandwich-ontray_no_gluten_sandwich tray2) 0)
)
    (:goal (and 
    (served child1)
    (served child2)
    (served child3)
    (served child4)
    (served child5)
    (served child6)
)))
